# Field names of the csv import file.

NAME                = 'Name'
PUBLISHER           = 'Publisher'
WEBSITE             = 'Website'
FILMSIMULATION      = 'Film Simulation'
BW_COLOR_MC         = 'BW Color MC'
BW_COLOR_WC         = 'BW Color WC'
GRAIN_EFFECT        = 'Grain Effect'
CCR_EFFECT          = 'CCR Effect'
CCRFX_BLUE          = 'CCR FX Blue'
WHITE_BALANCE       = 'White Balance'            
KELVIN              = 'Kelvin'
WHITE_BALANCE_B     = 'White Balance B'            
WHITE_BALANCE_R     = 'White Balance R'    
DYNAMIC_RANGE       = 'Dynamic Range'          
DRANGE_PRIORITY     = 'Dynamic Range Priority'
HIGHLIGHTS          = 'Highlights'                            
SHADOWS             = 'Shadows'   
SHARPNESS           = 'Sharpness'
COLOR               = 'Color'  
HIGH_ISONR          = 'High ISO NR'
CLARITY             = 'Clarity'
ISO_MIN             = 'ISO min'
ISO_MAX             = 'ISO max'
XTRANS_VERSION      = 'X-Trans'
